# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'hatchui.ui'
##
## Created by: Qt User Interface Compiler version 6.6.1
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide6.QtCore import (QCoreApplication, QDate, QDateTime, QLocale,
    QMetaObject, QObject, QPoint, QRect,
    QSize, QTime, QUrl, Qt)
from PySide6.QtGui import (QBrush, QColor, QConicalGradient, QCursor,
    QFont, QFontDatabase, QGradient, QIcon,
    QImage, QKeySequence, QLinearGradient, QPainter,
    QPalette, QPixmap, QRadialGradient, QTransform)
from PySide6.QtWidgets import (QApplication, QFrame, QHBoxLayout, QLabel,
    QLineEdit, QMainWindow, QPushButton, QSizePolicy,
    QStatusBar, QTabWidget, QVBoxLayout, QWidget)
import icon_rc

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        if not MainWindow.objectName():
            MainWindow.setObjectName(u"MainWindow")
        MainWindow.resize(1128, 709)
        icon = QIcon()
        icon.addFile(u":/hatch/icon/airplan.png", QSize(), QIcon.Normal, QIcon.Off)
        MainWindow.setWindowIcon(icon)
        MainWindow.setIconSize(QSize(36, 36))
        self.centralwidget = QWidget(MainWindow)
        self.centralwidget.setObjectName(u"centralwidget")
        self.Tab = QTabWidget(self.centralwidget)
        self.Tab.setObjectName(u"Tab")
        self.Tab.setGeometry(QRect(10, 0, 1081, 681))
        self.Tab.setLayoutDirection(Qt.LeftToRight)
        self.Tab.setIconSize(QSize(24, 24))
        self.Tab_1 = QWidget()
        self.Tab_1.setObjectName(u"Tab_1")
        self.Tab_1.setLayoutDirection(Qt.LeftToRight)
        self.btn_in_img = QPushButton(self.Tab_1)
        self.btn_in_img.setObjectName(u"btn_in_img")
        self.btn_in_img.setGeometry(QRect(0, 590, 91, 31))
        icon1 = QIcon()
        icon1.addFile(u":/hatch/icon/debit-card.png", QSize(), QIcon.Normal, QIcon.Off)
        self.btn_in_img.setIcon(icon1)
        self.btn_in_img.setIconSize(QSize(24, 24))
        self.btn_det_img = QPushButton(self.Tab_1)
        self.btn_det_img.setObjectName(u"btn_det_img")
        self.btn_det_img.setGeometry(QRect(110, 590, 81, 31))
        icon2 = QIcon()
        icon2.addFile(u":/hatch/icon/play.png", QSize(), QIcon.Normal, QIcon.Off)
        self.btn_det_img.setIcon(icon2)
        self.btn_det_img.setIconSize(QSize(24, 24))
        self.btn_save_img = QPushButton(self.Tab_1)
        self.btn_save_img.setObjectName(u"btn_save_img")
        self.btn_save_img.setGeometry(QRect(220, 590, 91, 31))
        icon3 = QIcon()
        icon3.addFile(u":/hatch/icon/forward.png", QSize(), QIcon.Normal, QIcon.Off)
        self.btn_save_img.setIcon(icon3)
        self.btn_save_img.setIconSize(QSize(24, 24))
        self.label_in_img = QLabel(self.Tab_1)
        self.label_in_img.setObjectName(u"label_in_img")
        self.label_in_img.setGeometry(QRect(0, 20, 511, 491))
        self.label_in_img.setTextFormat(Qt.AutoText)
        self.label_in_img.setPixmap(QPixmap(u":/newPrefix/pic/Hint.png"))
        self.label_in_img.setScaledContents(False)
        self.label_in_img.setAlignment(Qt.AlignCenter)
        self.label_in_img.setWordWrap(False)
        self.label_in_img.setIndent(-1)
        self.label_in_img.setTextInteractionFlags(Qt.LinksAccessibleByMouse)
        self.label_out_img = QLabel(self.Tab_1)
        self.label_out_img.setObjectName(u"label_out_img")
        self.label_out_img.setGeometry(QRect(540, 10, 511, 531))
        self.label_out_img.setTextFormat(Qt.AutoText)
        self.label_out_img.setPixmap(QPixmap(u":/newPrefix/pic/Hint.png"))
        self.label_out_img.setScaledContents(False)
        self.label_out_img.setAlignment(Qt.AlignCenter)
        self.label_out_img.setWordWrap(False)
        self.label_out_img.setIndent(-1)
        self.label_out_img.setTextInteractionFlags(Qt.LinksAccessibleByMouse)
        self.line = QFrame(self.Tab_1)
        self.line.setObjectName(u"line")
        self.line.setGeometry(QRect(520, 10, 20, 521))
        self.line.setFrameShape(QFrame.VLine)
        self.line.setFrameShadow(QFrame.Sunken)
        self.layoutWidget = QWidget(self.Tab_1)
        self.layoutWidget.setObjectName(u"layoutWidget")
        self.layoutWidget.setGeometry(QRect(482, 570, 151, 61))
        self.verticalLayout = QVBoxLayout(self.layoutWidget)
        self.verticalLayout.setObjectName(u"verticalLayout")
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout = QHBoxLayout()
        self.horizontalLayout.setObjectName(u"horizontalLayout")
        self.label_2 = QLabel(self.layoutWidget)
        self.label_2.setObjectName(u"label_2")

        self.horizontalLayout.addWidget(self.label_2)

        self.label_show_time = QLabel(self.layoutWidget)
        self.label_show_time.setObjectName(u"label_show_time")

        self.horizontalLayout.addWidget(self.label_show_time)


        self.verticalLayout.addLayout(self.horizontalLayout)

        self.horizontalLayout_3 = QHBoxLayout()
        self.horizontalLayout_3.setObjectName(u"horizontalLayout_3")
        self.label_4 = QLabel(self.layoutWidget)
        self.label_4.setObjectName(u"label_4")

        self.horizontalLayout_3.addWidget(self.label_4)

        self.label_show_class = QLabel(self.layoutWidget)
        self.label_show_class.setObjectName(u"label_show_class")

        self.horizontalLayout_3.addWidget(self.label_show_class)


        self.verticalLayout.addLayout(self.horizontalLayout_3)

        self.lineEdit_show = QLineEdit(self.Tab_1)
        self.lineEdit_show.setObjectName(u"lineEdit_show")
        self.lineEdit_show.setGeometry(QRect(710, 540, 361, 41))
        self.layoutWidget_2 = QWidget(self.Tab_1)
        self.layoutWidget_2.setObjectName(u"layoutWidget_2")
        self.layoutWidget_2.setGeometry(QRect(710, 590, 361, 31))
        self.horizontalLayout_4 = QHBoxLayout(self.layoutWidget_2)
        self.horizontalLayout_4.setObjectName(u"horizontalLayout_4")
        self.horizontalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.label_5 = QLabel(self.layoutWidget_2)
        self.label_5.setObjectName(u"label_5")

        self.horizontalLayout_4.addWidget(self.label_5)

        self.label_display = QLabel(self.layoutWidget_2)
        self.label_display.setObjectName(u"label_display")

        self.horizontalLayout_4.addWidget(self.label_display)

        self.btn_cho = QPushButton(self.Tab_1)
        self.btn_cho.setObjectName(u"btn_cho")
        self.btn_cho.setGeometry(QRect(340, 590, 81, 31))
        icon4 = QIcon()
        icon4.addFile(u":/hatch/icon/search.png", QSize(), QIcon.Normal, QIcon.Off)
        self.btn_cho.setIcon(icon4)
        self.btn_cho.setIconSize(QSize(24, 24))
        icon5 = QIcon()
        icon5.addFile(u":/hatch/icon/web-payment.png", QSize(), QIcon.Normal, QIcon.Off)
        self.Tab.addTab(self.Tab_1, icon5, "")
        self.Tab_2 = QWidget()
        self.Tab_2.setObjectName(u"Tab_2")
        self.label_outvideo = QLabel(self.Tab_2)
        self.label_outvideo.setObjectName(u"label_outvideo")
        self.label_outvideo.setGeometry(QRect(530, 20, 521, 531))
        self.label_outvideo.setTextFormat(Qt.AutoText)
        self.label_outvideo.setPixmap(QPixmap(u":/newPrefix/pic/Hint.png"))
        self.label_outvideo.setScaledContents(False)
        self.label_outvideo.setAlignment(Qt.AlignCenter)
        self.label_outvideo.setWordWrap(False)
        self.label_outvideo.setIndent(-1)
        self.label_outvideo.setTextInteractionFlags(Qt.LinksAccessibleByMouse)
        self.line_3 = QFrame(self.Tab_2)
        self.line_3.setObjectName(u"line_3")
        self.line_3.setGeometry(QRect(510, 20, 20, 541))
        self.line_3.setFrameShape(QFrame.VLine)
        self.line_3.setFrameShadow(QFrame.Sunken)
        self.btn_in_camera = QPushButton(self.Tab_2)
        self.btn_in_camera.setObjectName(u"btn_in_camera")
        self.btn_in_camera.setGeometry(QRect(140, 590, 101, 41))
        icon6 = QIcon()
        icon6.addFile(u":/hatch/icon/video.png", QSize(), QIcon.Normal, QIcon.Off)
        self.btn_in_camera.setIcon(icon6)
        self.label_invideo = QLabel(self.Tab_2)
        self.label_invideo.setObjectName(u"label_invideo")
        self.label_invideo.setGeometry(QRect(10, 30, 491, 531))
        self.label_invideo.setTextFormat(Qt.AutoText)
        self.label_invideo.setPixmap(QPixmap(u":/newPrefix/pic/Hint.png"))
        self.label_invideo.setScaledContents(False)
        self.label_invideo.setAlignment(Qt.AlignCenter)
        self.label_invideo.setWordWrap(False)
        self.label_invideo.setIndent(-1)
        self.label_invideo.setTextInteractionFlags(Qt.LinksAccessibleByMouse)
        self.btn_in_video = QPushButton(self.Tab_2)
        self.btn_in_video.setObjectName(u"btn_in_video")
        self.btn_in_video.setGeometry(QRect(0, 590, 121, 41))
        icon7 = QIcon()
        icon7.addFile(u":/hatch/icon/video-ad.png", QSize(), QIcon.Normal, QIcon.Off)
        self.btn_in_video.setIcon(icon7)
        self.btn_save_video = QPushButton(self.Tab_2)
        self.btn_save_video.setObjectName(u"btn_save_video")
        self.btn_save_video.setGeometry(QRect(260, 590, 91, 41))
        self.btn_save_video.setIcon(icon3)
        self.btn_save_video.setIconSize(QSize(24, 24))
        self.lineEdit_show_2 = QLineEdit(self.Tab_2)
        self.lineEdit_show_2.setObjectName(u"lineEdit_show_2")
        self.lineEdit_show_2.setGeometry(QRect(1630, 1160, 121, 21))
        self.layoutWidget_3 = QWidget(self.Tab_2)
        self.layoutWidget_3.setObjectName(u"layoutWidget_3")
        self.layoutWidget_3.setGeometry(QRect(510, 586, 171, 21))
        self.horizontalLayout_2 = QHBoxLayout(self.layoutWidget_3)
        self.horizontalLayout_2.setObjectName(u"horizontalLayout_2")
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.label_3 = QLabel(self.layoutWidget_3)
        self.label_3.setObjectName(u"label_3")

        self.horizontalLayout_2.addWidget(self.label_3)

        self.label_show_time_2 = QLabel(self.layoutWidget_3)
        self.label_show_time_2.setObjectName(u"label_show_time_2")

        self.horizontalLayout_2.addWidget(self.label_show_time_2)

        self.lineEdit_show2 = QLineEdit(self.Tab_2)
        self.lineEdit_show2.setObjectName(u"lineEdit_show2")
        self.lineEdit_show2.setGeometry(QRect(700, 580, 381, 31))
        self.layoutWidget_4 = QWidget(self.Tab_2)
        self.layoutWidget_4.setObjectName(u"layoutWidget_4")
        self.layoutWidget_4.setGeometry(QRect(510, 610, 171, 21))
        self.horizontalLayout_5 = QHBoxLayout(self.layoutWidget_4)
        self.horizontalLayout_5.setObjectName(u"horizontalLayout_5")
        self.horizontalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.label_6 = QLabel(self.layoutWidget_4)
        self.label_6.setObjectName(u"label_6")

        self.horizontalLayout_5.addWidget(self.label_6)

        self.label_show_class_2 = QLabel(self.layoutWidget_4)
        self.label_show_class_2.setObjectName(u"label_show_class_2")

        self.horizontalLayout_5.addWidget(self.label_show_class_2)

        self.btn_close_camera = QPushButton(self.Tab_2)
        self.btn_close_camera.setObjectName(u"btn_close_camera")
        self.btn_close_camera.setGeometry(QRect(360, 590, 101, 41))
        icon8 = QIcon()
        icon8.addFile(u":/hatch/icon/paused.png", QSize(), QIcon.Normal, QIcon.Off)
        self.btn_close_camera.setIcon(icon8)
        self.btn_close_camera.setIconSize(QSize(24, 24))
        self.label_7 = QLabel(self.Tab_2)
        self.label_7.setObjectName(u"label_7")
        self.label_7.setGeometry(QRect(700, 610, 81, 31))
        self.label_display_2 = QLabel(self.Tab_2)
        self.label_display_2.setObjectName(u"label_display_2")
        self.label_display_2.setGeometry(QRect(860, 620, 121, 21))
        self.Tab.addTab(self.Tab_2, icon7, "")
        self.Tab_3 = QWidget()
        self.Tab_3.setObjectName(u"Tab_3")
        self.label = QLabel(self.Tab_3)
        self.label.setObjectName(u"label")
        self.label.setGeometry(QRect(60, 20, 461, 121))
        font = QFont()
        font.setFamilies([u"\u9ed1\u4f53"])
        font.setPointSize(24)
        self.label.setFont(font)
        self.label_8 = QLabel(self.Tab_3)
        self.label_8.setObjectName(u"label_8")
        self.label_8.setGeometry(QRect(90, 120, 111, 121))
        self.label_8.setFont(font)
        self.label_9 = QLabel(self.Tab_3)
        self.label_9.setObjectName(u"label_9")
        self.label_9.setGeometry(QRect(560, -10, 511, 651))
        self.label_9.setPixmap(QPixmap(u":/message/icon/\u5fae\u4fe1\u56fe\u7247_20240408142458.jpg"))
        self.label_9.setScaledContents(True)
        self.label_9.setWordWrap(False)
        icon9 = QIcon()
        icon9.addFile(u":/hatch/icon/email.png", QSize(), QIcon.Normal, QIcon.Off)
        self.Tab.addTab(self.Tab_3, icon9, "")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QStatusBar(MainWindow)
        self.statusbar.setObjectName(u"statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)

        self.Tab.setCurrentIndex(2)
        self.btn_in_img.setDefault(False)
        self.btn_in_video.setDefault(False)


        QMetaObject.connectSlotsByName(MainWindow)
    # setupUi

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QCoreApplication.translate("MainWindow", u"\u673a\u573a\u5f02\u7269\u68c0\u6d4b\u7cfb\u7edf", None))
        self.btn_in_img.setText(QCoreApplication.translate("MainWindow", u"\u5bfc\u5165\u56fe\u7247", None))
#if QT_CONFIG(tooltip)
        self.btn_det_img.setToolTip(QCoreApplication.translate("MainWindow", u"\u70b9\u51fb\u5f00\u59cb\u68c0\u6d4b", None))
#endif // QT_CONFIG(tooltip)
        self.btn_det_img.setText(QCoreApplication.translate("MainWindow", u"\u5f00\u59cb\u68c0\u6d4b", None))
#if QT_CONFIG(tooltip)
        self.btn_save_img.setToolTip(QCoreApplication.translate("MainWindow", u"\u70b9\u51fb\u4fdd\u5b58\u68c0\u6d4b\u7ed3\u679c", None))
#endif // QT_CONFIG(tooltip)
        self.btn_save_img.setText(QCoreApplication.translate("MainWindow", u"\u4fdd\u5b58\u7ed3\u679c", None))
        self.label_in_img.setText("")
        self.label_out_img.setText("")
        self.label_2.setText(QCoreApplication.translate("MainWindow", u"\u68c0\u6d4b\u65f6\u95f4\uff1a", None))
        self.label_show_time.setText(QCoreApplication.translate("MainWindow", u"TextLabel", None))
        self.label_4.setText(QCoreApplication.translate("MainWindow", u"\u68c0\u6d4b\u7c7b\u522b\uff1a", None))
        self.label_show_class.setText(QCoreApplication.translate("MainWindow", u"TextLabel", None))
        self.label_5.setText(QCoreApplication.translate("MainWindow", u"\u7cfb\u7edf\u72b6\u6001\uff1a", None))
        self.label_display.setText(QCoreApplication.translate("MainWindow", u"TextLabel", None))
#if QT_CONFIG(tooltip)
        self.btn_cho.setToolTip("")
#endif // QT_CONFIG(tooltip)
        self.btn_cho.setText(QCoreApplication.translate("MainWindow", u"\u66f4\u6362\u6a21\u578b", None))
        self.Tab.setTabText(self.Tab.indexOf(self.Tab_1), QCoreApplication.translate("MainWindow", u"\u56fe\u7247\u68c0\u6d4b", None))
        self.label_outvideo.setText("")
#if QT_CONFIG(tooltip)
        self.btn_in_camera.setToolTip(QCoreApplication.translate("MainWindow", u"\u70b9\u51fb\u5f00\u59cb\u68c0\u6d4b", None))
#endif // QT_CONFIG(tooltip)
        self.btn_in_camera.setText(QCoreApplication.translate("MainWindow", u"\u68c0\u6d4b\u6444\u50cf\u5934", None))
        self.label_invideo.setText("")
#if QT_CONFIG(tooltip)
        self.btn_in_video.setToolTip(QCoreApplication.translate("MainWindow", u"\u70b9\u51fb\u8f93\u5165\u56fe\u7247", None))
#endif // QT_CONFIG(tooltip)
        self.btn_in_video.setText(QCoreApplication.translate("MainWindow", u"\u68c0\u6d4b\u89c6\u9891", None))
#if QT_CONFIG(tooltip)
        self.btn_save_video.setToolTip(QCoreApplication.translate("MainWindow", u"\u70b9\u51fb\u4fdd\u5b58\u68c0\u6d4b\u7ed3\u679c", None))
#endif // QT_CONFIG(tooltip)
        self.btn_save_video.setText(QCoreApplication.translate("MainWindow", u"\u4fdd\u5b58\u7ed3\u679c", None))
        self.label_3.setText(QCoreApplication.translate("MainWindow", u"\u68c0\u6d4b\u65f6\u95f4\uff1a", None))
        self.label_show_time_2.setText(QCoreApplication.translate("MainWindow", u"TextLabel", None))
        self.label_6.setText(QCoreApplication.translate("MainWindow", u"\u68c0\u6d4b\u7c7b\u522b\uff1a", None))
        self.label_show_class_2.setText(QCoreApplication.translate("MainWindow", u"TextLabel", None))
#if QT_CONFIG(tooltip)
        self.btn_close_camera.setToolTip(QCoreApplication.translate("MainWindow", u"\u70b9\u51fb\u4fdd\u5b58\u68c0\u6d4b\u7ed3\u679c", None))
#endif // QT_CONFIG(tooltip)
        self.btn_close_camera.setText(QCoreApplication.translate("MainWindow", u"\u5173\u95ed\u6444\u50cf\u5934", None))
        self.label_7.setText(QCoreApplication.translate("MainWindow", u"\u7cfb\u7edf\u72b6\u6001\uff1a", None))
        self.label_display_2.setText(QCoreApplication.translate("MainWindow", u"TextLabel", None))
        self.Tab.setTabText(self.Tab.indexOf(self.Tab_2), QCoreApplication.translate("MainWindow", u"\u89c6\u9891\u68c0\u6d4b", None))
        self.label.setText(QCoreApplication.translate("MainWindow", u"\u90ae\u7bb1\uff1aYonghengLiu@shu.edu.cn", None))
        self.label_8.setText(QCoreApplication.translate("MainWindow", u"QQ", None))
        self.label_9.setText("")
        self.Tab.setTabText(self.Tab.indexOf(self.Tab_3), QCoreApplication.translate("MainWindow", u"\u8054\u7cfb\u6211", None))
    # retranslateUi

